services:
  predict_api:
    build:
      context: ..
      dockerfile: dockerfiles/server/dockerfile
    networks:
      - app_network
    ports:
      - "8000:8000"
    env_file:
      - ../.env
  predict_ui:
    build:
      context: ..
      dockerfile: dockerfiles/client/dockerfile
    networks:
      - app_network
    ports:
      - "8501:8501"
    env_file:
      - ../.env    

networks:
  app_network:
